### ISSUE TITLE
Redirection forbidden

### ISSUE THREAD

**Issue by mukkoo** [welaika/wordpress_tools#10]
downloading wordpress I've this error:

```
Downloading WordPress 4.4.2 (it_IT)...
/~/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open-uri.rb:224:in `open_loop': redirection forbidden: http://downloads.wordpress.org/release/it_IT/wordpress-4.4.2.zip -> https://downloads.wordpress.org/release/it_IT/wordpress-4.4.2.zip (RuntimeError)
  from /~/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open-uri.rb:150:in `open_uri'
  from /~/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open-uri.rb:716:in `open'
  from /~/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/open-uri.rb:34:in `open'
  from /~/.rvm/gems/ruby-2.2.0@wordless/gems/thor-0.19.1/lib/thor/actions/file_manipulation.rb:82:in `get'
  from /~/.rvm/gems/ruby-2.2.0@wordless/gems/wordpress_tools-1.1.2/lib/wordpress_tools/wordpress.rb:38:in `download_wordpress'
  from /~/.rvm/gems/ruby-2.2.0@wordless/gems/wordpress_tools-1.1.2/lib/wordpress_tools/wordpress.rb:13:in `download'
  from /~/.rvm/gems/ruby-2.2.0@wordless/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  from /~/.rvm/gems/ruby-2.2.0@wordless/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  from /~/.rvm/gems/ruby-2.2.0@wordless/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  from /~/.rvm/gems/ruby-2.2.0@wordless/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
  from /~/.rvm/gems/ruby-2.2.0@wordless/gems/wordpress_tools-1.1.2/lib/wordpress_tools/cli.rb:19:in `new'
  from /~/.rvm/gems/ruby-2.2.0@wordless/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  from /~/.rvm/gems/ruby-2.2.0@wordless/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  from /~/.rvm/gems/ruby-2.2.0@wordless/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  from /~/.rvm/gems/ruby-2.2.0@wordless/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
  from /~/.rvm/gems/ruby-2.2.0@wordless/gems/wordless-1.1.1/lib/wordless/wordless_cli.rb:164:in `install_wordpress_and_wp_cli'
  from /~/.rvm/gems/ruby-2.2.0@wordless/gems/wordless-1.1.1/lib/wordless/wordless_cli.rb:27:in `start'
  from /~/.rvm/gems/ruby-2.2.0@wordless/gems/wordless-1.1.1/lib/wordless/cli.rb:16:in `new'
  from /~/.rvm/gems/ruby-2.2.0@wordless/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  from /~/.rvm/gems/ruby-2.2.0@wordless/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  from /~/.rvm/gems/ruby-2.2.0@wordless/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  from /~/.rvm/gems/ruby-2.2.0@wordless/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  from /~/.rvm/gems/ruby-2.2.0@wordless/gems/wordless-1.1.1/exe/wordless:8:in `<top (required)>'
  from /~/.rvm/gems/ruby-2.2.0@wordless/bin/wordless:23:in `load'
  from /~/.rvm/gems/ruby-2.2.0@wordless/bin/wordless:23:in `<main>'
  from /~/.rvm/gems/ruby-2.2.0@wordless/bin/ruby_executable_hooks:15:in `eval'
  from /~/.rvm/gems/ruby-2.2.0@wordless/bin/ruby_executable_hooks:15:in `<main>'
```

I've found this solution http://stackoverflow.com/questions/27407938/ruby-open-uri-redirect-forbidden

**Comment by delphaber** [comment]
Already fixed
